# Site settings
title: Jaehwan's Portfolio
description: Jaehwan's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://devJHLee.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: "Jaehwan Lee"
user_description: 
user_title: Android Developer
email: ljh951103@naver.com
github_username: hwanine


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']