# Site settings
title: Will Arevalo Blog
description: This is only other blog of a Enthusiastic programmer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Will Developer
user_description: <p>¡Hola!</p> <p>Si estas aca en busca de temas relacionados con Servers, Hacks, Lenguajes de programacion y mas…</p> <p>Has llegado al sitio indicado.</p>
user_title: Software Developer
email: thewillfap@gmail.com
twitter_username: Unthinkable_Man
github_username:  WillArevalo
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
